const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const saved=JSON.parse(localStorage.getItem('historyEgeProgress')||'{}');
const catalog=$('#catalog'), cards=$('#moduleCards'); let activeModule='8.1';
function statusLabel(s){return s==='ready'?'Готово':s==='active'?'В работе':'Скоро'}
CATALOG.forEach(m=>{const a=document.createElement('div');a.className='catalog-group '+(m.status||'');a.innerHTML=`<button data-module="${m.id}"><span>${m.id}</span><b>${m.title}</b><em>${statusLabel(m.status)}</em></button>${m.children?`<div class="children">${m.children.map(c=>`<button data-module="${c.id}" class="${c.status}"><span>${c.id}</span>${c.title}<em>${statusLabel(c.status)}</em></button>`).join('')}</div>`:''}`;catalog.append(a);cards.insertAdjacentHTML('beforeend',`<article class="module-card ${m.status}"><span>${m.id}</span><h3>${m.title}</h3><p>${m.source||'Кодификатор ЕГЭ 2026'}</p><b>${statusLabel(m.status)}</b></article>`)});
function visualHTML(v){
  if(v.type==='document') return `<article class="document-card"><div class="document-label">Исторический источник</div><h3>${v.title}</h3>${v.date?`<time>${v.date}</time>`:''}${v.quote?`<blockquote>${v.quote}</blockquote>`:''}<div class="document-analysis"><b>Простыми словами</b><p>${v.explain||''}</p></div>${v.significance?`<div class="document-significance"><b>Историческое значение</b><p>${v.significance}</p></div>`:''}${v.ege?`<div class="map-ege"><b>Для ЕГЭ</b><p>${v.ege}</p></div>`:''}${v.check?`<details class="document-check"><summary>Проверь себя</summary><p>${v.check}</p>${v.answer?`<div class="document-answer"><b>Ответ:</b> ${v.answer}</div>`:''}</details>`:''}${v.source?`<small>Источник: ${v.source}</small>`:''}</article>`;
  const isMap=v.type==='map';
  return `<figure class="${isMap?'map-figure':'photo-figure'}"><button class="media-open" type="button" data-src="${v.src}" aria-label="Открыть изображение крупно"><img src="${v.src}" loading="lazy" alt="${v.caption}"><span>Увеличить ↗</span></button><figcaption>${v.title?`<h4>${v.title}</h4>`:''}<p>${v.caption}</p>${v.explain?`<div class="map-reading"><b>${isMap?'Что увидеть на карте':'Почему это важно'}</b><p>${v.explain}</p></div>`:''}${v.ege?`<div class="map-ege"><b>Для ЕГЭ</b><p>${v.ege}</p></div>`:''}</figcaption></figure>`;
}
function topicHTML(t,i,visuals={}){return `<details class="topic" id="${t.id}"><summary><input class="check" data-id="${t.id}" type="checkbox" ${saved[t.id]?'checked':''}><span class="num">${i+1}</span><div><h2>${t.title}</h2><small>${t.code.slice(0,2).join(' • ')}</small></div></summary><div class="body"><div class="code"><h4>Соответствие кодификатору</h4><ul>${t.code.map(x=>`<li>${x}</li>`).join('')}</ul><div class="source">${t.pages}</div></div><div class="text">${t.text.map(x=>`<p>${x}</p>`).join('')}</div>${(visuals[t.id]||[]).length?`<div class="visuals">${visuals[t.id].map(visualHTML).join('')}</div>`:''}<div class="grid"><div class="box"><h4>Причины / предпосылки</h4><ul>${t.causes.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="box"><h4>Итоги / последствия</h4><ul>${t.results.map(x=>`<li>${x}</li>`).join('')}</ul></div></div>${t.significance?`<div class="significance"><b>Историческое значение</b><p>${t.significance}</p></div>`:''}<div class="ege"><b>Что запомнить для ЕГЭ</b><p>${t.ege}</p></div><div class="question"><b>Самопроверка</b><p>${t.question}</p><textarea placeholder="Запишите ответ своими словами…"></textarea></div></div></details>`}
function renderTopics(course,contentSel,navSel,visuals={}){const content=$(contentSel),nav=$(navSel);course.topics.forEach((t,i)=>{nav.insertAdjacentHTML('beforeend',`<a href="#${t.id}">${i+1}</a>`);content.insertAdjacentHTML('beforeend',topicHTML(t,i,visuals))})}
renderTopics(COURSE81,'#content81','#topicNav81',VISUALS81); renderTopics(COURSE82,'#content82','#topicNav82',VISUALS82); renderTopics(COURSE83,'#content83','#topicNav83',VISUALS83); renderTopics(COURSE84,'#content84','#topicNav84',VISUALS84); renderTopics(COURSE,'#content','#topicNav',VISUALS); renderTopics(COURSE92,'#content92','#topicNav92',{}); renderTopics(COURSE93,'#content93','#topicNav93',VISUALS93); renderTopics(COURSE94,'#content94','#topicNav94',VISUALS94);renderTopics(COURSE101,'#content101','#topicNav101',VISUALS101);
render101Extras();
function render92Extras(){const o=$('#overview92');o.innerHTML=`<section class="learning-overview"><h2>Маршрут по теме</h2><p>Сначала просмотрите ключевые даты, затем изучайте теорию по смысловым блокам. После каждой темы ответьте на вопрос, а в конце пройдите тест.</p><div class="timeline">${COURSE92.timeline.map(x=>`<div><time>${x[0]}</time><span>${x[1]}</span></div>`).join('')}</div></section>`;
const s=$('#summary92');s.innerHTML=`<section class="final-block"><h2>Что запомнить для ЕГЭ</h2><div class="remember-grid">${COURSE92.remember.map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block"><h2>Термины</h2><div class="terms-grid">${COURSE92.terms.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section><section class="final-block test-block"><h2>Проверочный тест</h2><p class="test-intro">Выберите один вариант ответа. После проверки появится объяснение.</p><div id="test92">${COURSE92.tests.map((t,i)=>`<fieldset data-correct="${t.correct}" data-explain="${t.explain.replace(/"/g,'&quot;')}"><legend>${i+1}. ${t.q}</legend>${t.a.map((a,j)=>`<label><input type="radio" name="q92_${i}" value="${j}"><span>${a}</span></label>`).join('')}<div class="test-feedback"></div></fieldset>`).join('')}</div><button id="checkTest92" class="primary">Проверить тест</button><div id="testResult92" class="test-result"></div></section>`;$('#checkTest92').onclick=()=>{let correct=0,answered=0;$$('#test92 fieldset').forEach(f=>{const c=+f.dataset.correct,sel=f.querySelector('input:checked'),fb=f.querySelector('.test-feedback');f.classList.remove('ok','bad');if(sel){answered++;if(+sel.value===c){correct++;f.classList.add('ok');fb.textContent='Верно. '+f.dataset.explain}else{f.classList.add('bad');fb.textContent='Неверно. '+f.dataset.explain}}else fb.textContent='Выберите вариант ответа.'});$('#testResult92').textContent=`Результат: ${correct} из ${COURSE92.tests.length}. Отвечено: ${answered}.`}}

function render82Extras(){const o=$('#overview82');o.innerHTML=`<section class="learning-overview"><h2>Маршрут по теме</h2><p>Сталинград → прорыв блокады Ленинграда → Курская дуга → Днепр → партизаны, коллаборационизм и первые процессы.</p><div class="timeline">${COURSE82.timeline.map(x=>`<div><time>${x[0]}</time><span>${x[1]}</span></div>`).join('')}</div></section>`;const s=$('#summary82');s.innerHTML=`<section class="final-block"><h2>Что обязательно запомнить для ЕГЭ</h2><div class="remember-grid">${COURSE82.remember.map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block"><h2>Персоналии ЕГЭ</h2><div class="persons-grid">${COURSE82.persons.map(p=>`<article class="person-ege"><h3>${p.name}</h3><p><b>Роль:</b> ${p.role}</p><p class="person-ege-note"><b>Для ЕГЭ:</b> ${p.ege}</p></article>`).join('')}</div></section><section class="final-block"><h2>Термины</h2><div class="terms-grid">${COURSE82.terms.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section><section class="final-block"><h2>Частые ошибки</h2><div class="remember-grid"><div>18 января 1943 г. — прорыв, а не полное снятие блокады Ленинграда.</div><div>Операция «Уран» — окружение, «Кольцо» — ликвидация окружённой группировки.</div><div>Поныри относятся к северному фасу Курской дуги, Прохоровка — к южному.</div><div>Не сводите значение Прохоровки к утверждению о полном уничтожении немецких танков.</div><div>Коллаборационизм имел разные формы и мотивы, но преступления пособников подлежали ответственности.</div></div></section><section class="final-block test-block"><h2>Проверочный тест</h2><p class="test-intro">25 заданий по коренному перелому.</p><div id="test82">${COURSE82.tests.map((t,i)=>`<fieldset data-correct="${t.correct}" data-explain="${t.explain.replace(/"/g,'&quot;')}"><legend>${i+1}. ${t.q}</legend>${t.a.map((a,j)=>`<label><input type="radio" name="q82_${i}" value="${j}"><span>${a}</span></label>`).join('')}<div class="test-feedback"></div></fieldset>`).join('')}</div><button id="checkTest82" class="primary">Проверить тест</button><div id="testResult82" class="test-result"></div></section>`;$('#checkTest82').onclick=()=>{let correct=0,answered=0;$$('#test82 fieldset').forEach(f=>{const c=+f.dataset.correct,sel=f.querySelector('input:checked'),fb=f.querySelector('.test-feedback');f.classList.remove('ok','bad');if(sel){answered++;if(+sel.value===c){correct++;f.classList.add('ok');fb.textContent='Верно. '+f.dataset.explain}else{f.classList.add('bad');fb.textContent='Неверно. '+f.dataset.explain}}else fb.textContent='Выберите вариант ответа.'});const percent=Math.round(correct/COURSE82.tests.length*100);$('#testResult82').textContent=`Результат: ${correct} из ${COURSE82.tests.length} (${percent}%). Отвечено: ${answered}.`}}
function render81Extras(){const o=$('#overview81');o.innerHTML=`<section class="learning-overview"><h2>Маршрут по теме</h2><p>Изучайте материал по хронологии: планы сторон → кампания 1941 г. → битва за Москву → события 1942 г. → оккупация, тыл и сопротивление. Карты из атласа встроены в соответствующие темы; под каждой картой дано пояснение, что именно нужно увидеть и запомнить для ЕГЭ.</p><div class="timeline">${COURSE81.timeline.map(x=>`<div><time>${x[0]}</time><span>${x[1]}</span></div>`).join('')}</div></section>`;
const s=$('#summary81');s.innerHTML=`<section class="final-block"><h2>Что обязательно запомнить для ЕГЭ</h2><div class="remember-grid">${COURSE81.remember.map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block"><h2>Персоналии ЕГЭ</h2><p class="test-intro">Военачальники, государственные деятели и герои, которых важно связывать с событиями первого периода войны.</p><div class="persons-grid">${COURSE81.persons.map(p=>`<article class="person-ege"><h3>${p.name}</h3><p><b>Роль:</b> ${p.role}</p><p class="person-ege-note"><b>Для ЕГЭ:</b> ${p.ege}</p></article>`).join('')}</div></section><section class="final-block"><h2>Термины</h2><div class="terms-grid">${COURSE81.terms.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section><section class="final-block"><h2>Частые ошибки</h2><div class="remember-grid"><div>Не объясняйте поражения 1941 г. только внезапностью нападения — нужен комплекс причин.</div><div>Не путайте оборонительный этап Московской битвы с неудачной Ржевско-Вяземской операцией 1942 г.</div><div>Контрнаступление под Сталинградом относится уже к теме 8.2.</div><div>Приказ № 227 не следует представлять единственной причиной стойкости Красной армии.</div><div>План «Ост» — не военная операция, а колониальная программа нацистов.</div></div></section><section class="final-block test-block"><h2>Проверочный тест</h2><p class="test-intro">30 заданий по первому периоду войны, включая вопросы на персоналии. После проверки появится объяснение каждого ответа.</p><div id="test81">${COURSE81.tests.map((t,i)=>`<fieldset data-correct="${t.correct}" data-explain="${t.explain.replace(/"/g,'&quot;')}"><legend>${i+1}. ${t.q}</legend>${t.a.map((a,j)=>`<label><input type="radio" name="q81_${i}" value="${j}"><span>${a}</span></label>`).join('')}<div class="test-feedback"></div></fieldset>`).join('')}</div><button id="checkTest81" class="primary">Проверить тест</button><div id="testResult81" class="test-result"></div></section>`;$('#checkTest81').onclick=()=>{let correct=0,answered=0;$$('#test81 fieldset').forEach(f=>{const c=+f.dataset.correct,sel=f.querySelector('input:checked'),fb=f.querySelector('.test-feedback');f.classList.remove('ok','bad');if(sel){answered++;if(+sel.value===c){correct++;f.classList.add('ok');fb.textContent='Верно. '+f.dataset.explain}else{f.classList.add('bad');fb.textContent='Неверно. '+f.dataset.explain}}else fb.textContent='Выберите вариант ответа.'});const percent=Math.round(correct/COURSE81.tests.length*100);$('#testResult81').textContent=`Результат: ${correct} из ${COURSE81.tests.length} (${percent}%). Отвечено: ${answered}.`}}
render81Extras(); render82Extras();




function render101Extras(){
const o=$('#overview101');

o.innerHTML=`
<section class="learning-overview">
<h2>Маршрут по теме</h2>
<p>Распад СССР → реформы 1990-х → политический кризис 1993 года → Конституция РФ → Чечня → кризис 1998 года → смена власти в 1999 году.</p>

<div class="timeline">
${COURSE101.timeline.map(x=>`<div><span>${x}</span></div>`).join('')}
</div>

</section>`;
const t=$('#terms101');

t.innerHTML=`
<section class="final-block">
<h2>Термины ЕГЭ</h2>

<div class="terms-grid">
${COURSE101.terms.map(x=>`<div>${x}</div>`).join('')}
</div>

</section>`;
const t=$('#terms101');

t.innerHTML=`
<section class="final-block">
<h2>Термины ЕГЭ</h2>

<div class="terms-grid">
${COURSE101.terms.map(x=>`<div>${x}</div>`).join('')}
</div>

</section>`;
}

function render83Extras(){
  const o=$('#overview83');
  o.innerHTML=`<section class="learning-overview"><h2>Маршрут по теме</h2><p>Мобилизация управления → эвакуация и военная экономика → труд и повседневность → духовная жизнь → партизанское движение → значение единства фронта и тыла.</p><div class="timeline">${COURSE83.timeline.map(x=>`<div><time>${x[0]}</time><span>${x[1]}</span></div>`).join('')}</div></section>`;
  const personCard=p=>`<article class="person-ege person-ege-rich">${p.image?`<button class="person-media media-open" type="button" data-src="${p.image}"><img src="${p.image}" alt="${p.name}" loading="lazy"><span>Увеличить ↗</span></button>`:`<div class="person-monogram">${p.name.split(' ').filter(x=>/^[А-ЯЁ]/.test(x)).slice(0,2).map(x=>x[0]).join('')}</div>`}<div class="person-content"><h3>${p.name}</h3><p><b>Роль:</b> ${p.role}</p>${p.fact?`<p><b>Исторический факт:</b> ${p.fact}</p>`:''}<p class="person-ege-note"><b>Для ЕГЭ:</b> ${p.ege}</p>${p.check?`<details class="person-check"><summary>Мини-проверка</summary><p>${p.check}</p><div><b>Ответ:</b> ${p.answer||''}</div></details>`:''}</div></article>`;
  const expanded=(COURSE83.expanded||[]).map((x,i)=>`<details class="expanded-task"><summary>${i+1}. ${x.q}</summary><div class="expanded-answer"><b>Возможный ответ</b><p>${x.a}</p></div></details>`).join('');
  const s=$('#summary83');
  s.innerHTML=`<section class="final-block"><h2>Что обязательно запомнить для ЕГЭ</h2><div class="remember-grid">${COURSE83.remember.map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block"><h2>Персоналии ЕГЭ</h2><p class="test-intro">Связывайте каждую фамилию с конкретным направлением деятельности в годы войны.</p><div class="persons-grid persons-grid-rich">${COURSE83.persons.map(personCard).join('')}</div></section><section class="final-block"><h2>Термины</h2><div class="terms-grid">${COURSE83.terms.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section><section class="final-block"><h2>Частые ошибки</h2><div class="remember-grid"><div>Не путайте ГКО, сосредоточивший государственную власть, и Ставку ВГК, руководившую вооружёнными силами.</div><div>Эвакуация означала не только вывоз населения, но и перемещение оборудования, кадров и учреждений.</div><div>Карточная система регулировала распределение дефицита, но не устраняла нехватку продуктов.</div><div>Смягчение политики в отношении РПЦ относится прежде всего к 1943 г.</div><div>«Рельсовая война» и «Концерт» — разные партизанские операции 1943 г.</div></div></section><section class="final-block test-block"><h2>Итоговый тест</h2><p class="test-intro">30 заданий по экономике, тылу, культуре, Церкви и партизанскому движению. После проверки появится объяснение каждого ответа.</p><div id="test83">${COURSE83.tests.map((t,i)=>`<fieldset data-correct="${t.correct}" data-explain="${t.explain.replace(/"/g,'&quot;')}"><legend>${i+1}. ${t.q}</legend>${t.a.map((a,j)=>`<label><input type="radio" name="q83_${i}" value="${j}"><span>${a}</span></label>`).join('')}<div class="test-feedback"></div></fieldset>`).join('')}</div><button id="checkTest83" class="primary">Проверить тест</button><div id="testResult83" class="test-result"></div></section><section class="final-block"><h2>Задания с развёрнутым ответом</h2><p class="test-intro">Сначала сформулируйте ответ самостоятельно, затем раскройте карточку для проверки.</p><div class="expanded-list">${expanded}</div></section><section class="final-block quick83"><span class="eyebrow">Быстрое повторение</span><h2>ЕГЭ за 60 секунд</h2><div class="quick-grid">${(COURSE83.quick||[]).map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block completion83"><h2>Завершение модуля</h2><p>Отметьте модуль завершённым после изучения теории, источников, персоналий и выполнения теста.</p><button id="complete83" class="primary">Модуль пройден</button><div id="complete83Status" class="completion-status"></div></section>`;
  $('#checkTest83').onclick=()=>{let correct=0,answered=0;$$('#test83 fieldset').forEach(f=>{const c=+f.dataset.correct,sel=f.querySelector('input:checked'),fb=f.querySelector('.test-feedback');f.classList.remove('ok','bad');if(sel){answered++;if(+sel.value===c){correct++;f.classList.add('ok');fb.textContent='Верно. '+f.dataset.explain}else{f.classList.add('bad');fb.textContent='Неверно. '+f.dataset.explain}}else fb.textContent='Выберите вариант ответа.'});const percent=Math.round(correct/COURSE83.tests.length*100);$('#testResult83').textContent=`Результат: ${correct} из ${COURSE83.tests.length} (${percent}%). Отвечено: ${answered}.`;localStorage.setItem('historyEgeTest83',JSON.stringify({correct,total:COURSE83.tests.length,percent,date:new Date().toISOString()}))};
  const completeBtn=$('#complete83'),completeStatus=$('#complete83Status');
  const syncComplete=()=>{const done=localStorage.getItem('historyEgeModule83Complete')==='1';completeBtn.textContent=done?'Модуль пройден ✓':'Модуль пройден';completeBtn.classList.toggle('completed',done);completeStatus.textContent=done?'Прогресс сохранён в этом браузере.':''};
  completeBtn.onclick=()=>{const done=localStorage.getItem('historyEgeModule83Complete')==='1';localStorage.setItem('historyEgeModule83Complete',done?'0':'1');syncComplete()};syncComplete();
}

function render84Extras(){
  const o=$('#overview84');
  o.innerHTML=`<section class="learning-overview"><h2>Маршрут по теме</h2><p>Освобождение территории СССР → операция «Багратион» → освобождение Европы → Берлин и капитуляция Германии → союзнические конференции → война с Японией → ООН и итоги войны.</p><div class="timeline">${COURSE84.timeline.map(x=>`<div><time>${x[0]}</time><span>${x[1]}</span></div>`).join('')}</div></section>`;
  const documents=Object.values(VISUALS84).flat().filter(v=>v.type==='document');
  const personCard=p=>`<article class="person-ege"><h3>${p.name}</h3><p><b>Роль:</b> ${p.role}</p><p class="person-ege-note"><b>Для ЕГЭ:</b> ${p.ege}</p></article>`;
  const s=$('#summary84');
  s.innerHTML=`<section class="final-block documents84"><span class="eyebrow">Отдельный раздел</span><h2>Документы и исторические источники</h2><p class="test-intro">Семь ключевых источников темы 8.4 с объяснением, историческим значением и мини-проверкой.</p><div class="visuals documents-collection">${documents.map(visualHTML).join('')}</div></section><section class="final-block"><h2>Что обязательно запомнить для ЕГЭ</h2><div class="remember-grid">${COURSE84.remember.map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block"><h2>Персоналии ЕГЭ</h2><div class="persons-grid">${COURSE84.persons.map(personCard).join('')}</div></section><section class="final-block"><h2>Термины</h2><div class="terms-grid">${COURSE84.terms.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section><section class="final-block"><h2>Частые ошибки</h2><div class="remember-grid"><div>Не путайте капитуляцию Берлина 2 мая и капитуляцию Германии 8/9 мая 1945 г.</div><div>Ялтинская конференция состоялась в феврале, Потсдамская — в июле–августе 1945 г.</div><div>Политика четырёх «Д» относится к послевоенному устройству Германии.</div><div>Великая Отечественная война завершилась в мае, Вторая мировая — 2 сентября 1945 г.</div><div>Операция «Багратион» связана с освобождением Белоруссии, а не со штурмом Берлина.</div></div></section><section class="final-block test-block"><h2>Проверочный тест</h2><p class="test-intro">30 заданий по завершающему этапу Великой Отечественной и Второй мировой войны.</p><div id="test84">${COURSE84.tests.map((t,i)=>`<fieldset data-correct="${t.correct}" data-explain="${t.explain.replace(/"/g,'&quot;')}"><legend>${i+1}. ${t.q}</legend>${t.a.map((a,j)=>`<label><input type="radio" name="q84_${i}" value="${j}"><span>${a}</span></label>`).join('')}<div class="test-feedback"></div></fieldset>`).join('')}</div><button id="checkTest84" class="primary">Проверить тест</button><div id="testResult84" class="test-result"></div></section>`;
  $('#checkTest84').onclick=()=>{let correct=0,answered=0;$$('#test84 fieldset').forEach(f=>{const c=+f.dataset.correct,sel=f.querySelector('input:checked'),fb=f.querySelector('.test-feedback');f.classList.remove('ok','bad');if(sel){answered++;if(+sel.value===c){correct++;f.classList.add('ok');fb.textContent='Верно. '+f.dataset.explain}else{f.classList.add('bad');fb.textContent='Неверно. '+f.dataset.explain}}else fb.textContent='Выберите вариант ответа.'});const percent=Math.round(correct/COURSE84.tests.length*100);$('#testResult84').textContent=`Результат: ${correct} из ${COURSE84.tests.length} (${percent}%). Отвечено: ${answered}.`};
}
render83Extras(); render84Extras();

function render93Extras(){const o=$('#overview93');o.innerHTML=`<section class="learning-overview"><h2>Маршрут по теме</h2><p>Изучите политический курс, реформы и причины их свёртывания, затем сопоставьте достижения науки и социальной сферы с нарастанием застойных тенденций. Иллюстрации взяты из учебника и сопровождаются учебными подписями.</p><div class="timeline">${COURSE93.timeline.map(x=>`<div><time>${x[0]}</time><span>${x[1]}</span></div>`).join('')}</div></section>`;
const s=$('#summary93');s.innerHTML=`<section class="final-block"><h2>Что запомнить для ЕГЭ</h2><div class="remember-grid">${COURSE93.remember.map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block"><h2>Термины</h2><div class="terms-grid">${COURSE93.terms.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section><section class="final-block test-block"><h2>Большой проверочный тест</h2><p class="test-intro">18 заданий по политике, экономике, обществу, культуре и внешней политике. После проверки к каждому ответу появится объяснение.</p><div id="test93">${COURSE93.tests.map((t,i)=>`<fieldset data-correct="${t.correct}" data-explain="${t.explain.replace(/"/g,'&quot;')}"><legend>${i+1}. ${t.q}</legend>${t.a.map((a,j)=>`<label><input type="radio" name="q93_${i}" value="${j}"><span>${a}</span></label>`).join('')}<div class="test-feedback"></div></fieldset>`).join('')}</div><button id="checkTest93" class="primary">Проверить тест</button><div id="testResult93" class="test-result"></div></section>`;$('#checkTest93').onclick=()=>{let correct=0,answered=0;$$('#test93 fieldset').forEach(f=>{const c=+f.dataset.correct,sel=f.querySelector('input:checked'),fb=f.querySelector('.test-feedback');f.classList.remove('ok','bad');if(sel){answered++;if(+sel.value===c){correct++;f.classList.add('ok');fb.textContent='Верно. '+f.dataset.explain}else{f.classList.add('bad');fb.textContent='Неверно. '+f.dataset.explain}}else fb.textContent='Выберите вариант ответа.'});const percent=Math.round(correct/COURSE93.tests.length*100);$('#testResult93').textContent=`Результат: ${correct} из ${COURSE93.tests.length} (${percent}%). Отвечено: ${answered}.`}}
render93Extras();
function render94Extras(){const o=$('#overview94');o.innerHTML=`<section class="learning-overview"><h2>Маршрут по теме</h2><p>Проследите, как попытка обновить социалистическую систему переросла в политическую демократизацию, кризис союзного государства и распад СССР. Особое внимание уделите точной хронологии 1988–1991 гг.</p><div class="timeline">${COURSE94.timeline.map(x=>`<div><time>${x[0]}</time><span>${x[1]}</span></div>`).join('')}</div></section>`;
const s=$('#summary94');s.innerHTML=`<section class="final-block"><h2>Что обязательно запомнить для ЕГЭ</h2><div class="remember-grid">${COURSE94.remember.map(x=>`<div>${x}</div>`).join('')}</div></section><section class="final-block"><h2>Частые ошибки на ЕГЭ</h2><div class="remember-grid"><div>Не отождествляйте ускорение 1985 г. с полноценным переходом к рынку.</div><div>Гласность не означала немедленной отмены всех ограничений свободы слова.</div><div>Отмена статьи 6 произошла в 1990 г., а первый Съезд народных депутатов — в 1989 г.</div><div>ГКЧП действовал 19–21 августа, а Беловежские соглашения подписаны 8 декабря 1991 г.</div><div>Распад СССР нельзя объяснить одной причиной: это результат комплекса кризисов.</div></div></section><section class="final-block"><h2>Термины</h2><div class="terms-grid">${COURSE94.terms.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</div></section><section class="final-block test-block"><h2>Большой проверочный тест</h2><p class="test-intro">25 заданий по реформам, политике, национальным движениям, внешней политике и распаду СССР. После проверки появится объяснение.</p><div id="test94">${COURSE94.tests.map((t,i)=>`<fieldset data-correct="${t.correct}" data-explain="${t.explain.replace(/"/g,'&quot;')}"><legend>${i+1}. ${t.q}</legend>${t.a.map((a,j)=>`<label><input type="radio" name="q94_${i}" value="${j}"><span>${a}</span></label>`).join('')}<div class="test-feedback"></div></fieldset>`).join('')}</div><button id="checkTest94" class="primary">Проверить тест</button><div id="testResult94" class="test-result"></div></section>`;$('#checkTest94').onclick=()=>{let correct=0,answered=0;$$('#test94 fieldset').forEach(f=>{const c=+f.dataset.correct,sel=f.querySelector('input:checked'),fb=f.querySelector('.test-feedback');f.classList.remove('ok','bad');if(sel){answered++;if(+sel.value===c){correct++;f.classList.add('ok');fb.textContent='Верно. '+f.dataset.explain}else{f.classList.add('bad');fb.textContent='Неверно. '+f.dataset.explain}}else fb.textContent='Выберите вариант ответа.'});const percent=Math.round(correct/COURSE94.tests.length*100);$('#testResult94').textContent=`Результат: ${correct} из ${COURSE94.tests.length} (${percent}%). Отвечено: ${answered}.`}}
render94Extras();


const mediaModal=document.createElement('div');mediaModal.className='media-modal';mediaModal.innerHTML='<button class="media-close" aria-label="Закрыть">×</button><img alt="Увеличенное историческое изображение">';document.body.append(mediaModal);
document.addEventListener('click',e=>{const b=e.target.closest('.media-open');if(b){mediaModal.querySelector('img').src=b.dataset.src;mediaModal.classList.add('open');document.body.classList.add('modal-open')}if(e.target===mediaModal||e.target.closest('.media-close')){mediaModal.classList.remove('open');document.body.classList.remove('modal-open')}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){mediaModal.classList.remove('open');document.body.classList.remove('modal-open')}});

function update(){const all=$$('.check'),done=all.filter(x=>x.checked).length,p=Math.round(done/all.length*100);$('#overallBar').style.width=p+'%';$('#overallText').textContent=p+'%';[['#content81','#bar81','#progressText81'],['#content82','#bar82','#progressText82'],['#content83','#bar83','#progressText83'],['#content84','#bar84','#progressText84'],['#content','#bar','#progressText'],['#content92','#bar92','#progressText92'],['#content93','#bar93','#progressText93'],['#content94','#bar94','#progressText94']].forEach(([c,b,t])=>{const checks=$$(c+' .check'),d=checks.filter(x=>x.checked).length,pp=Math.round(d/checks.length*100);$(b).style.width=pp+'%';$(t).textContent=`Изучено ${d} из ${checks.length} тем — ${pp}%`})}
function showModule(id){activeModule=id;$('#home').classList.add('hidden');$('#dashboard').classList.add('hidden');$('#module81').classList.toggle('hidden',id!=='8.1');$('#module82').classList.toggle('hidden',id!=='8.2');$('#module83').classList.toggle('hidden',id!=='8.3');$('#module84').classList.toggle('hidden',id!=='8.4');$('#module91').classList.toggle('hidden',id!=='9.1');$('#module92').classList.toggle('hidden',id!=='9.2');$('#module93').classList.toggle('hidden',id!=='9.3');$('#module94').classList.toggle('hidden',id!=='9.4');$('#module101').classList.toggle('hidden',id!=='10.1');window.scrollTo({top:0,behavior:'smooth'})}
function showHome(){
  [
    '#module81',
    '#module82',
    '#module83',
    '#module84',
    '#module91',
    '#module92',
    '#module93',
    '#module94',
    '#module101'
  ].forEach(id=>{
    $(id)?.classList.add('hidden');
  });

  $('#home').classList.remove('hidden');
  $('#dashboard').classList.remove('hidden');

  window.scrollTo({
    top:0,
    behavior:'smooth'
  });


  }

$('#start81')?.addEventListener('click',()=>showModule('8.1'));
$('#start82')?.addEventListener('click',()=>showModule('8.2'));
$('#start83')?.addEventListener('click',()=>showModule('8.3'));
$('#start84')?.addEventListener('click',()=>showModule('8.4'));
$('#start91')?.addEventListener('click',()=>showModule('9.1'));
$('#start92')?.addEventListener('click',()=>showModule('9.2'));
$('#start93')?.addEventListener('click',()=>showModule('9.3'));
$('#start94')?.addEventListener('click',()=>showModule('9.4'));
$('#start101')?.addEventListener('click',()=>showModule('10.1'));
catalog.onclick=e=>{const b=e.target.closest('button[data-module]');if(!b)return;if(['8.1','8.2','8.3','8.4','9.1','9.2','9.3','9.4','10.1'].includes(b.dataset.module))showModule(b.dataset.module)};
document.addEventListener('change',e=>{if(e.target.classList.contains('check')){saved[e.target.dataset.id]=e.target.checked;localStorage.setItem('historyEgeProgress',JSON.stringify(saved));update()}});document.addEventListener('click',e=>{if(e.target.classList.contains('check'))e.stopPropagation()});
$('#expand').onclick=()=>$$('#content .topic').forEach(x=>x.open=true);$('#collapse').onclick=()=>$$('#content .topic').forEach(x=>x.open=false);$$('.expand').forEach(b=>b.onclick=()=>$$('#'+b.dataset.target+' .topic').forEach(x=>x.open=true));$$('.collapse').forEach(b=>b.onclick=()=>$$('#'+b.dataset.target+' .topic').forEach(x=>x.open=false));
$('#search').oninput=()=>{const q=$('#search').value.toLowerCase().trim();if(q.length>1)showModule(activeModule);const container=activeModule==='8.1'?'#content81':activeModule==='8.2'?'#content82':activeModule==='8.3'?'#content83':activeModule==='8.4'?'#content84':activeModule==='9.4'?'#content94':activeModule==='9.3'?'#content93':activeModule==='9.2'?'#content92':
activeModule==='10.1'?'#content101':
'#content',course=activeModule==='8.1'?COURSE81:activeModule==='8.2'?COURSE82:activeModule==='8.3'?COURSE83:activeModule==='8.4'?COURSE84:activeModule==='9.4'?COURSE94:activeModule==='9.3'?COURSE93:activeModule==='9.2'?COURSE92:
activeModule==='10.1'?COURSE101:
COURSE;$$(container+' .topic').forEach((el,i)=>el.classList.toggle('search-hidden',q.length>1&&!JSON.stringify(course.topics[i]).toLowerCase().includes(q)))};
$('#theme').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('historyTheme',document.documentElement.dataset.theme)};document.documentElement.dataset.theme=localStorage.getItem('historyTheme')||'light';$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');update();
$$('.backHome').forEach(btn=>{
  btn.onclick=()=>showHome();
});
